apiVersion: v1
kind: Service
metadata:
  name: upday-svc
spec:
  selector:
    app: upday
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: upday
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: upday
    spec:
       containers:
        - name: upday

          image: index.docker.io/prashanthsunny/upday:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe: #To check the pod's started  before it's served with traffic
            httpGet:
               path: /actuator/health
               port: 8080
          livenessProbe:  #If livenessProbe fails, then the pod is subjected to its restart policy
            httpGet:
              path: /actuator/health
              port: 8080
